In [1]:
import numpy as np
import pandas as pd

In [2]:
atEstablishment = [[1,1], [1,0], [0,1], [1,1], [0,0], [1,0], [1,1]]

In [3]:
fightOccurred = [0,1,0,0,0,1,0]

In [4]:
atEstablishment = np.array(atEstablishment)

In [5]:
fightOccurred = np.array(fightOccurred)

In [6]:
atEstablishment.shape

(7, 2)

In [7]:
fightOccurred.shape

(7,)

In [9]:
fightOccurred[1]

1

In [10]:
atEstablishment[1]

array([1, 0])

In [14]:
np.dot(atEstablishment[1], [-1,1])

-1

In [36]:
n = atEstablishment.shape[1]
policy_Array = np.zeros((n*(n-1), n))

In [37]:
policy_Array

array([[ 0.,  0.],
       [ 0.,  0.]])

In [38]:
index = 0
for i in range(n):
    for j in range(n):
        if i != j:
            policy_Array[index][i] = 1
            policy_Array[index][j] = -1
            index += 1

In [39]:
policy_Array

array([[ 1., -1.],
       [-1.,  1.]])

In [50]:
total_H = range(n*(n-1))
total_H

[0, 1]

In [51]:
final_output = []

In [52]:
for episode in range(atEstablishment.shape[0]):
    print "Now is episode: ", episode
    print 'Now H is:', total_H
    
    prediction_pool = []
    for policy_index in total_H:
        
        policy = policy_Array[policy_index]
        isFighting = 0
          
        if np.dot(atEstablishment[episode], policy) > 0.9:
            isFighting = 1
        
        prediction_pool.append(isFighting)
            
    if len(set(prediction_pool)) == 1:
        final_output.append(prediction_pool[0])
    else:
        final_output.append(-1)
        
        for policy_check_index in total_H:
            policy_check = policy_Array[policy_check_index]
            predict_label = 0
            if np.dot(atEstablishment[episode], policy_check) > 0.9:
                predict_label = 1
            if predict_label != fightOccurred[episode]:
                total_H.remove(policy_check_index)
        

Now is episode:  0
Now H is: [0, 1]
Now is episode:  1
Now H is: [0, 1]
Now is episode:  2
Now H is: [0]
Now is episode:  3
Now H is: [0]
Now is episode:  4
Now H is: [0]
Now is episode:  5
Now H is: [0]
Now is episode:  6
Now H is: [0]


In [53]:
final_output

[0, -1, 0, 0, 0, 1, 0]